# Generated by Django 3.2.4 on 2021-06-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/produce/None/no-img.jpg', upload_to='media/produce', verbose_name='Ảnh sản phẩm')),
                ('sale_off', models.IntegerField(default=0, verbose_name='Khuyến mãi')),
                ('price', models.BigIntegerField(default=0, verbose_name='Giá bán')),
                ('describe', models.TextField(verbose_name='Mô tả')),
                ('produce', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.produces')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'item',
            },
        ),
    ]
