# Generated by Django 3.2.4 on 2021-06-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210604_0015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produces',
        ),
    ]
