# Generated by Django 3.2.4 on 2021-06-02 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Khác'), (1, 'Nam'), (2, 'Nữ')], default=0, verbose_name='Gender')),
                ('id_selfie', models.ImageField(default='media/profile/None/no-img.jpg', upload_to='media/profile', verbose_name='Selfie')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customer',
                'db_table': 'customer',
            },
        ),
    ]
