# Generated by Django 3.2.4 on 2021-06-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_selfie',
            field=models.ImageField(default='media/profile/1.jpg', upload_to='media/profile', verbose_name='Selfie'),
        ),
    ]
