# Generated by Django 3.2.4 on 2021-06-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produces', '0003_itembook_itemclothes_itemelectro'),
        ('customers', '0002_alter_customer_id_selfie'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeElectro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BigIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produces.itemelectro')),
            ],
            options={
                'verbose_name': 'Yêu thích đồ điện tử',
                'verbose_name_plural': 'Yêu thích đồ điện tử',
                'db_table': 'like_electro',
            },
        ),
        migrations.CreateModel(
            name='LikeClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BigIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produces.itemclothes')),
            ],
            options={
                'verbose_name': 'Yêu thích quần áo',
                'verbose_name_plural': 'Yêu thích quần áo',
                'db_table': 'like_clothes',
            },
        ),
        migrations.CreateModel(
            name='LikeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BigIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produces.itembook')),
            ],
            options={
                'verbose_name': 'Yêu thích sách',
                'verbose_name_plural': 'Yêu thích sách',
                'db_table': 'like_book',
            },
        ),
        migrations.CreateModel(
            name='CommentElectro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('review', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produces.itemelectro')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Đánh giá về đồ điện tử',
                'verbose_name_plural': 'Đánh giá về đồ điện tử',
                'db_table': 'comment_electro',
            },
        ),
        migrations.CreateModel(
            name='CommentClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('review', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produces.itemclothes')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Đánh giá về quần áo',
                'verbose_name_plural': 'Đánh giá về quần áo',
                'db_table': 'comment_clothes',
            },
        ),
        migrations.CreateModel(
            name='CommentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('review', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produces.itembook')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Đánh giá về sách',
                'verbose_name_plural': 'Đánh giá về sách',
                'db_table': 'comment_book',
            },
        ),
    ]
