# Generated by Django 3.2.4 on 2021-06-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produces', '0003_itembook_itemclothes_itemelectro'),
        ('customers', '0003_commentbook_commentclothes_commentelectro_likebook_likeclothes_likeelectro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartElectro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produces.itemelectro')),
            ],
            options={
                'verbose_name': 'Giỏ hàng điện tử',
                'verbose_name_plural': 'Giỏ hàng điện tử',
                'db_table': 'cart_electro',
            },
        ),
        migrations.CreateModel(
            name='CartClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produces.itemclothes')),
            ],
            options={
                'verbose_name': 'Giỏ hàng quần áo',
                'verbose_name_plural': 'Giỏ hàng quần áo',
                'db_table': 'clothes_cart',
            },
        ),
        migrations.CreateModel(
            name='CartBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produces.itembook')),
            ],
            options={
                'verbose_name': 'Giỏ hàng sách',
                'verbose_name_plural': 'giỏ hàng sách',
                'db_table': 'cart_book',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(blank=True, related_name='tb_cart_book', to='customers.CartBook')),
                ('clothes', models.ManyToManyField(blank=True, related_name='tb_cart_clothes', to='customers.CartClothes')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('electros', models.ManyToManyField(blank=True, related_name='tb_cart_electro', to='customers.CartElectro')),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'giỏ hàng sách',
                'db_table': 'cart',
            },
        ),
    ]
