# Generated by Django 3.2.4 on 2021-06-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_cart_cartbook_cartclothes_cartelectro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbook',
            name='real_pay',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartbook',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartclothes',
            name='real_pay',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartclothes',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartelectro',
            name='real_pay',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartelectro',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
