# Generated by Django 3.2.4 on 2021-06-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210604_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbook',
            name='real_pay',
        ),
        migrations.RemoveField(
            model_name='cartclothes',
            name='real_pay',
        ),
        migrations.RemoveField(
            model_name='cartelectro',
            name='real_pay',
        ),
    ]
