# Generated by Django 3.2.4 on 2021-06-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20210604_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
