# Generated by Django 3.2.4 on 2021-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_cart_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Người nhận',
                'verbose_name_plural': 'Người nhận',
                'db_table': 'receiver',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('fee', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vận chuyển',
                'verbose_name_plural': 'Vận chuyển',
                'db_table': 'shipment',
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Giỏ hàng', 'verbose_name_plural': 'Giỏ hàng'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='tb_cart_book', to='customers.CartBook'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='clothes',
            field=models.ManyToManyField(blank=True, null=True, related_name='tb_cart_clothes', to='customers.CartClothes'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='electros',
            field=models.ManyToManyField(blank=True, null=True, related_name='tb_cart_electro', to='customers.CartElectro'),
        ),
    ]
