# Generated by Django 3.2.4 on 2021-06-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('into_money', models.BigIntegerField(blank=True, null=True)),
                ('payment_methods', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.receiver')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.shipment')),
            ],
            options={
                'verbose_name': 'Đặt hàng',
                'verbose_name_plural': 'Đặt hàng',
                'db_table': 'order',
            },
        ),
    ]
