# Generated by Django 3.2.4 on 2021-06-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_receiver_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbook',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartclothes',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartelectro',
            name='item',
        ),
    ]
