# Generated by Django 3.2.4 on 2021-06-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produces', '0003_itembook_itemclothes_itemelectro'),
        ('customers', '0014_auto_20210605_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbook',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.cart'),
        ),
        migrations.AddField(
            model_name='cartbook',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produces.itembook'),
        ),
        migrations.AddField(
            model_name='cartclothes',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.cart'),
        ),
        migrations.AddField(
            model_name='cartclothes',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produces.itemclothes'),
        ),
        migrations.AddField(
            model_name='cartelectro',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.cart'),
        ),
        migrations.AddField(
            model_name='cartelectro',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produces.itemelectro'),
        ),
    ]
