# Generated by Django 3.2.4 on 2021-06-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20210605_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
