# Generated by Django 3.2.4 on 2021-06-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.PositiveSmallIntegerField(choices=[(0, 'Thanh toán khi nhận hàng'), (1, 'Thanh toán qua thẻ ngân hàng'), (0, 'Thanh toán qua ví momo ')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Khác'), (1, 'Nam'), (2, 'Nữ')], default=0),
        ),
    ]
